In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import seaborn as sns
import matplotlib.pyplot as plt
from helper_functions import *

In [2]:
healthy_data = pd.read_csv("healthy_data.csv")
damaged_data = pd.read_csv("damaged_data.csv")

In [3]:
healthy_data.columns = healthy_data.columns.str.replace('H', 'S')
damaged_data.columns = damaged_data.columns.str.replace('D', 'S')

In [4]:
common_cols = healthy_data.columns.intersection(damaged_data.columns)
new_healthy_data = healthy_data[common_cols]
new_damage_data = damaged_data[common_cols]

In [31]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
healthy_data_scaled = scaler.fit_transform(new_healthy_data)
damaged_data_scaled = scaler.fit_transform(new_damage_data)

In [32]:
healthy_data_scaled = pd.DataFrame(healthy_data_scaled, columns=common_cols)
healthy_data_scaled.head()

,S1_AN3,S1_AN4,S1_AN5,S1_AN6,S1_AN7,S1_AN8,S1_AN9,S1_AN10,S1_Speed,S10_AN3,...,S8_Speed,S9_AN3,S9_AN4,S9_AN5,S9_AN6,S9_AN7,S9_AN8,S9_AN9,S9_AN10,S9_Speed
0,-0.723576,0.392498,-1.297769,-0.614003,1.667086,-0.625596,-0.899137,-0.257976,-0.139202,-0.300280,...,-0.146120,-0.962544,-0.470591,-0.729940,-0.926940,0.627689,0.505150,0.159640,1.100185,-0.139099
1,-1.234167,0.511543,-1.660811,-0.459000,1.490400,-0.670187,-1.098397,0.074411,-0.139214,0.292083,...,-0.132995,-0.987447,-0.694311,-0.606769,-1.178175,-1.301779,0.386680,0.108698,0.662957,-0.139003
2,-1.869075,-0.116025,-1.866484,1.075076,-0.285620,-0.303620,-1.273740,0.215844,-0.139138,0.371839,...,-0.143562,-0.516670,-0.987843,-0.374638,-0.368722,-0.149072,0.412373,0.070361,0.683713,-0.139036
3,-2.372654,0.160905,-1.729564,0.850225,-0.163598,-0.434786,-1.421717,-0.011301,-0.139167,0.704012,...,-0.135136,-0.257355,-1.762532,-0.157594,-0.830744,0.401177,0.105178,0.055994,0.782126,-0.139079
4,-2.352900,0.805045,-1.347538,0.365857,-0.514413,-0.533591,-1.519198,0.029443,-0.139171,0.629267,...,-0.141690,-0.515747,-2.004539,-0.454372,-0.757931,0.173926,0.076073,0.072844,1.110596,-0.139058

In [33]:
damaged_data_scaled = pd.DataFrame(damaged_data_scaled, columns=common_cols)
damaged_data_scaled.head()

,S1_AN3,S1_AN4,S1_AN5,S1_AN6,S1_AN7,S1_AN8,S1_AN9,S1_AN10,S1_Speed,S10_AN3,...,S8_Speed,S9_AN3,S9_AN4,S9_AN5,S9_AN6,S9_AN7,S9_AN8,S9_AN9,S9_AN10,S9_Speed
0,0.895728,-0.803695,-0.591388,0.614164,0.710708,-0.703050,2.922758,-0.699389,0.376621,-0.664111,...,-1.132203,-1.031972,-0.394024,-0.629858,0.256553,0.161773,-0.461559,-0.030850,0.447162,0.760050
1,0.554000,-0.893921,-0.601161,-0.200874,-0.132659,-0.740684,1.918620,-1.762388,0.377013,-0.371384,...,-1.161689,-1.514797,-0.609447,-0.195637,-0.189910,-0.877539,-0.567150,-0.956453,0.451713,0.766234
2,0.281159,-0.977420,-0.332221,-1.006774,-0.055339,-0.600491,0.682754,-2.317633,0.327797,-0.371251,...,-1.074982,-1.624911,-0.198575,0.125305,-0.574307,-1.529601,-0.625100,-2.154858,0.218933,0.781502
3,0.262082,-1.184668,0.145119,-0.477495,0.225374,-0.688108,-0.468001,-2.007984,0.383092,-0.364958,...,-0.826111,-1.500216,0.052300,0.202461,0.219372,-1.281138,-0.770572,-1.979969,0.000548,0.666900
4,0.596071,-1.245294,0.287394,0.211928,0.078648,-1.190833,-1.278761,-1.355123,0.333679,-0.389228,...,-0.804193,-1.377311,0.237910,0.176557,0.481446,-0.762504,-0.792092,-0.839424,-0.335464,0.419917

In [51]:
healthy_data_scaled.to_csv('healthy_data_scaled.csv')
damaged_data_scaled.to_csv('damaged-data_scaled.csv')

In [34]:
healthy_data_scaled.columns

Index(['S1_AN3', 'S1_AN4', 'S1_AN5', 'S1_AN6', 'S1_AN7', 'S1_AN8', 'S1_AN9',
       'S1_AN10', 'S1_Speed', 'S10_AN3', 'S10_AN4', 'S10_AN5', 'S10_AN6',
       'S10_AN7', 'S10_AN8', 'S10_AN9', 'S10_AN10', 'S10_Speed', 'S2_AN3',
       'S2_AN4', 'S2_AN5', 'S2_AN6', 'S2_AN7', 'S2_AN8', 'S2_AN9', 'S2_AN10',
       'S2_Speed', 'S3_AN3', 'S3_AN4', 'S3_AN5', 'S3_AN6', 'S3_AN7', 'S3_AN8',
       'S3_AN9', 'S3_AN10', 'S3_Speed', 'S4_AN3', 'S4_AN4', 'S4_AN5', 'S4_AN6',
       'S4_AN7', 'S4_AN8', 'S4_AN9', 'S4_AN10', 'S4_Speed', 'S5_AN3', 'S5_AN4',
       'S5_AN5', 'S5_AN6', 'S5_AN7', 'S5_AN8', 'S5_AN9', 'S5_AN10', 'S5_Speed',
       'S6_AN3', 'S6_AN4', 'S6_AN5', 'S6_AN6', 'S6_AN7', 'S6_AN8', 'S6_AN9',
       'S6_AN10', 'S6_Speed', 'S7_AN3', 'S7_AN4', 'S7_AN5', 'S7_AN6', 'S7_AN7',
       'S7_AN8', 'S7_AN9', 'S7_AN10', 'S7_Speed', 'S8_AN3', 'S8_AN4', 'S8_AN5',
       'S8_AN6', 'S8_AN7', 'S8_AN8', 'S8_AN9', 'S8_AN10', 'S8_Speed', 'S9_AN3',
       'S9_AN4', 'S9_AN5', 'S9_AN6', 'S9_AN7', 'S9_AN8', 'S9_AN9', 'S9_AN10',
       'S9_Speed'],
      dtype='object')

In [35]:
columns_to_drop = ['S1_Speed', 'S10_Speed', 'S2_Speed', 'S3_Speed', 'S4_Speed', 'S5_Speed', 'S6_Speed', 'S7_Speed', 'S8_Speed', 'S9_Speed']

In [36]:
healthy_data_scaled.drop(columns=columns_to_drop, inplace=True)
healthy_data_scaled.head()

,S1_AN3,S1_AN4,S1_AN5,S1_AN6,S1_AN7,S1_AN8,S1_AN9,S1_AN10,S10_AN3,S10_AN4,...,S8_AN9,S8_AN10,S9_AN3,S9_AN4,S9_AN5,S9_AN6,S9_AN7,S9_AN8,S9_AN9,S9_AN10
0,-0.723576,0.392498,-1.297769,-0.614003,1.667086,-0.625596,-0.899137,-0.257976,-0.300280,-1.081048,...,0.034937,0.482556,-0.962544,-0.470591,-0.729940,-0.926940,0.627689,0.505150,0.159640,1.100185
1,-1.234167,0.511543,-1.660811,-0.459000,1.490400,-0.670187,-1.098397,0.074411,0.292083,-1.387102,...,0.205688,0.662812,-0.987447,-0.694311,-0.606769,-1.178175,-1.301779,0.386680,0.108698,0.662957
2,-1.869075,-0.116025,-1.866484,1.075076,-0.285620,-0.303620,-1.273740,0.215844,0.371839,-1.355736,...,0.411365,1.110746,-0.516670,-0.987843,-0.374638,-0.368722,-0.149072,0.412373,0.070361,0.683713
3,-2.372654,0.160905,-1.729564,0.850225,-0.163598,-0.434786,-1.421717,-0.011301,0.704012,-1.103686,...,0.644672,0.965342,-0.257355,-1.762532,-0.157594,-0.830744,0.401177,0.105178,0.055994,0.782126
4,-2.352900,0.805045,-1.347538,0.365857,-0.514413,-0.533591,-1.519198,0.029443,0.629267,-1.037734,...,0.899541,1.007834,-0.515747,-2.004539,-0.454372,-0.757931,0.173926,0.076073,0.072844,1.110596

In [37]:
damaged_data_scaled.drop(columns=columns_to_drop, inplace=True)
damaged_data_scaled.head()

,S1_AN3,S1_AN4,S1_AN5,S1_AN6,S1_AN7,S1_AN8,S1_AN9,S1_AN10,S10_AN3,S10_AN4,...,S8_AN9,S8_AN10,S9_AN3,S9_AN4,S9_AN5,S9_AN6,S9_AN7,S9_AN8,S9_AN9,S9_AN10
0,0.895728,-0.803695,-0.591388,0.614164,0.710708,-0.703050,2.922758,-0.699389,-0.664111,0.160863,...,-0.417304,1.278104,-1.031972,-0.394024,-0.629858,0.256553,0.161773,-0.461559,-0.030850,0.447162
1,0.554000,-0.893921,-0.601161,-0.200874,-0.132659,-0.740684,1.918620,-1.762388,-0.371384,0.072225,...,-0.453317,1.799884,-1.514797,-0.609447,-0.195637,-0.189910,-0.877539,-0.567150,-0.956453,0.451713
2,0.281159,-0.977420,-0.332221,-1.006774,-0.055339,-0.600491,0.682754,-2.317633,-0.371251,-0.345302,...,-0.534556,1.664202,-1.624911,-0.198575,0.125305,-0.574307,-1.529601,-0.625100,-2.154858,0.218933
3,0.262082,-1.184668,0.145119,-0.477495,0.225374,-0.688108,-0.468001,-2.007984,-0.364958,-0.507710,...,-0.543835,1.062826,-1.500216,0.052300,0.202461,0.219372,-1.281138,-0.770572,-1.979969,0.000548
4,0.596071,-1.245294,0.287394,0.211928,0.078648,-1.190833,-1.278761,-1.355123,-0.389228,-0.175210,...,-1.313324,0.748429,-1.377311,0.237910,0.176557,0.481446,-0.762504,-0.792092,-0.839424,-0.335464

In [38]:
healthy_data_scaled['State'] = 1
damaged_data_scaled['State'] = 0

In [39]:
dfGbxData = pd.concat([healthy_data_scaled, damaged_data_scaled]).reset_index()
dfGbxData = dfGbxData.sample(frac=1, random_state=42).reset_index(drop=True)
dfGbxData.head()

,index,S1_AN3,S1_AN4,S1_AN5,S1_AN6,S1_AN7,S1_AN8,S1_AN9,S1_AN10,S10_AN3,...,S8_AN10,S9_AN3,S9_AN4,S9_AN5,S9_AN6,S9_AN7,S9_AN8,S9_AN9,S9_AN10,State
0,2143565,1.420337,1.881011,-0.654054,0.607794,-2.277450,-0.089638,-1.465412,0.059851,-0.172568,...,0.477662,0.361707,-1.262515,-0.594722,1.400610,-0.453948,-0.919567,-1.838908,1.043588,0
1,2047403,0.554301,-0.245624,0.692329,-0.980663,-0.113706,-0.200461,-1.223790,1.581912,0.830841,...,0.553576,0.113724,0.946500,2.355975,1.583904,0.614686,-1.271579,-1.186459,-1.083682,1
2,1069280,1.928160,0.165260,0.362086,0.801961,0.951499,1.317670,-0.041674,0.154458,1.899838,...,-0.690641,-0.123076,0.975741,-1.388849,-2.134483,1.584930,-1.171591,-1.301129,0.892893,0
3,221000,0.904828,-0.466777,0.142159,-1.509096,1.150754,-0.970794,-0.500436,0.623257,0.580116,...,-0.219432,-0.343507,0.709591,-0.536802,-2.002629,0.774856,-1.588236,-0.050984,1.007349,1
4,740116,0.367642,2.494176,-0.394378,-0.191852,-0.963240,0.931387,-0.263939,-0.782581,-0.534985,...,-0.132466,0.656162,0.751740,1.976403,1.049799,0.685856,-0.632241,-1.600392,0.046892,1

In [ ]:
features = dfGbxData.columns[1:-1]
sensor_readings = dfGbxData.melt(
    id_vars=['State'],
    value_vars=features,
    var_name='sensor',
    value_name='reading'
)

In [50]:
sensor_readings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 384000000 entries, 0 to 383999999
Data columns (total 3 columns):
 #   Column   Dtype
---  ------   -----
 0   State    int64
 1   sensor   object
 2   reading  float64
dtypes: float64(1), int64(1), object(1)
memory usage: 8.6+ GB

In [52]:
dfGbxData.to_csv('gbx_scaled_data_with_state.csv')

In [53]:
sensor_readings.to_csv('all_sensor_data.csv')